on: push
name: TOC Generator
jobs:
  generateTOC:
    name: Generate TOC
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: 'README*.md, */README*.md'          
          GITHUB_TOKEN: ${{ github.token }}
